services:
  - type: web
    name: coverband-demo
    env: docker
    plan: free
    buildCommand: docker build -t coverband-demo .
    startCommand: ./bin/rails server
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: REDIS_URL
        sync: false
